spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=tuiglesia;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=calama1.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.sql.init.mode=never

spring.security.user.name=admin
spring.security.user.password=admin

