# Generated by Django 5.2.5 on 2025-08-24 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iglesia',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Iglesia',
                'verbose_name_plural': 'Iglesias',
                'db_table': 'iglesias',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('ministerio', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('bautismo', models.BooleanField(default=False)),
                ('discipulado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('iglesia', models.ForeignKey(db_column='iglesia_id', on_delete=django.db.models.deletion.CASCADE, to='core.iglesia')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'miembros',
            },
        ),
        migrations.CreateModel(
            name='NuevoMiembro',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('invitado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('notas_seguimiento', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('iglesia', models.ForeignKey(db_column='iglesia_id', on_delete=django.db.models.deletion.CASCADE, to='core.iglesia')),
            ],
            options={
                'verbose_name': 'Nuevo Miembro',
                'verbose_name_plural': 'Nuevos Miembros',
                'db_table': 'nuevos_miembros',
            },
        ),
        migrations.CreateModel(
            name='Oracion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('solicitante', models.CharField(max_length=255)),
                ('para_quien', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondida', 'Respondida')], default='pendiente', max_length=15)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('iglesia', models.ForeignKey(db_column='iglesia_id', on_delete=django.db.models.deletion.CASCADE, to='core.iglesia')),
            ],
            options={
                'verbose_name': 'Oración',
                'verbose_name_plural': 'Oraciones',
                'db_table': 'oraciones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('pastor', 'Pastor'), ('admin', 'Administrador')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('iglesia', models.ForeignKey(db_column='iglesia_id', on_delete=django.db.models.deletion.CASCADE, to='core.iglesia')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
    ]
